---
namespace: lava
name: lava
version: 1.0.0
readme: README.md
authors:
  - Magma Dev Team
description: Ansible Collection for Lava
license_file: LICENSE
tags:
  - crypto
  - lava
  - lavanet
  - blockchain
  - infrastructure
  - linux
repository: https://github.com/lavanet/ansible
documentation: https://github.com/lavanet/ansible
issues: https://github.com/lavanet/ansible/issues
build_ignore:
  - .config
  - .github
  - .gitignore
  - changelogs
  - roles/*/molecule
  - tests
  - "*test-requirements.txt"
  - "*.tar.gz"
