---
- name: Lava Provider
  hosts: "{{ ansible_limit | default(omit) }}"
  user: ubuntu
  vars_files:
    - vars/main.yml
  vars:
    chain_id: testnet
    user_name: ubuntu # os username
    domain: mycooldomain.com # your primary domain
    log_level: warn # log level for lavap
    lavap:
      version: v2.0.3 # lavap version(check the most recent release)
    force_selected_lavap: false # for testing purpose you can force selected lavap, and turn off lavavisor control of it
    go_install: "yes"
    go_version: 1.20.5
    lavavisor: "yes"
    lavavisor_version: v2.0.3 # lavavisor version(check the most recent release)
    cache:
      enabled: true
      address: 127.0.0.1:20100
      metrics_port: 20200
      logs: # this is cache related logs
        level: warn
        format: json
  roles:
    - role: cache
      tags: cache
    - role: provider
      tags: provider
