---
- name: Append lavavisor configuration
  become: true
  block:
    - name: Insert/Update lavavisor provider configuration
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'lavavisor_config.yml.j2') }}"
        path: /home/{{ user_name }}/.lavavisor/config.yml
        backup: true
        marker: "## {mark} LAVA PROVIDER ANSIBLE MANAGED BLOCK ##"
